"use client";
import { Card } from "@/components/ui/card";
import { PwrcCoin } from "@/components/brand/pwrc-coin";
import { SolanaIcon } from "@/components/ui/icons";
import { useAgents } from "@/hooks/use-agents";
import { useSkills } from "@/hooks/use-skills";
import { useSystemHealth } from "@/hooks/use-system-health";
import { SOLANA_CLUSTER } from "@/lib/solana/config";
const assets=[["Solar Farm North","4.2 MW"],["Wind Site West","12.1 MW"],["Battery North","2.0 MWh / 72%"],["Microgrid 03","+1.8 MWh"]];
export function ContextPanel(){
  const health=useSystemHealth(); const {enabled:agents}=useAgents(); const {enabled:skills}=useSkills(); const aiCount=health?.aiConfiguredCount??0;
  const rows=[["Portfolio","All assets",true],["Time Range","Last 24 hours",true],["AI Providers",health?`${aiCount} configured`:"Checking…",health?aiCount>0:null],["Helius",health?(health.services.helius?"Configured":"Public RPC fallback"):"Checking…",health?health.services.helius:null]] as const;
  return <aside className="hidden w-[292px] shrink-0 space-y-4 border-l bg-[var(--background)] p-4 xl:block"><Card className="p-4"><div className="flex items-center justify-between"><div className="text-xs font-bold">CONTEXT</div><span className="rounded-full bg-[var(--muted)] px-2 py-1 text-[9px] font-semibold">LIVE CONFIG</span></div><div className="mt-4 flex items-center gap-2 rounded-xl border p-3"><SolanaIcon size={22}/><div><div className="text-xs font-semibold">Solana</div><div className="text-xs text-[var(--muted-foreground)]">{SOLANA_CLUSTER}</div></div><span className="ml-auto size-2 rounded-full bg-emerald-500"/></div><div className="mt-4 space-y-4">{rows.map(([a,b,state])=><div key={a} className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold">{a}</div><div className="text-xs text-[var(--muted-foreground)]">{b}</div></div><span className={`mt-1.5 size-2 rounded-full ${state===true?"bg-emerald-500":state===false?"bg-amber-500":"bg-slate-400"}`}/></div>)}</div></Card><Card className="p-4"><div className="flex items-center justify-between"><div className="text-xs font-bold">GRIDLLM RUNTIME</div><span className="text-[10px] text-[var(--muted-foreground)]">Policy-bound</span></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-[var(--muted)] p-2"><div className="text-lg font-bold">{agents.length}</div><div className="text-[10px] text-[var(--muted-foreground)]">Agents</div></div><div className="rounded-lg bg-[var(--muted)] p-2"><div className="text-lg font-bold">{skills.length}</div><div className="text-[10px] text-[var(--muted-foreground)]">Skills</div></div></div></Card><Card className="p-4"><div className="flex items-center justify-between"><div className="text-xs font-bold">ACTIVE ASSETS</div><span className="text-[10px] text-[var(--muted-foreground)]">Sample portfolio</span></div><div className="mt-4 space-y-4">{assets.map(([a,b])=><div key={a} className="flex items-center justify-between"><div><div className="text-xs font-semibold">{a}</div><div className="text-xs text-[var(--muted-foreground)]">{b}</div></div><span className="size-2 rounded-full bg-emerald-500"/></div>)}</div></Card><Card className="overflow-hidden p-4"><div className="flex items-center justify-between"><div className="text-xs font-bold">PWRC TOKEN</div><span className="rounded-full border px-2 py-1 text-[9px] font-semibold text-[var(--muted-foreground)]">REFERENCE</span></div><div className="mt-4 flex items-center gap-3"><PwrcCoin size={62}/><div><div className="font-bold">PWRC</div><div className="text-xs text-[var(--muted-foreground)]">PowerChain Token</div><div className="mt-1 text-xl font-bold">$0.422</div></div></div><button className="mt-4 w-full rounded-lg border py-2 text-xs font-semibold transition hover:bg-[var(--muted)]">View PWRC analytics →</button></Card></aside>
}
